name: CI

on: [push, pull_request]

jobs:
  unit-test:
    strategy:
      matrix:
        # GitHub Actions replaces 5.0 with 5 so we have to be specific here
        swift: [5.0.3, 5.1, 5.2]
    runs-on: ubuntu-latest
    container: swift:${{ matrix.swift }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: swift build
      - name: Test
        run: swift test
